In [1]:

from pathlib import Path
import pandas as pd

# Carpeta donde guardamos los archivos originales
carpeta_datos = Path("../data/raw")

# Buscar archivos CSV
archivos_csv = list(carpeta_datos.glob("*.csv"))

print("Archivos CSV encontrados:", len(archivos_csv))

for archivo in archivos_csv:
    print("-", archivo.name)

Archivos CSV encontrados: 2
- netflix_movies_detailed_up_to_2025.csv
- netflix_tv_shows_detailed_up_to_2025.csv

In [2]:

from pathlib import Path
import pandas as pd

# Ubicación de los archivos originales
carpeta_datos = Path("../data/raw")

# Localizar los CSV automáticamente
archivos = list(carpeta_datos.glob("*.csv"))

# Identificar películas y series por el nombre del archivo
archivo_peliculas = next(
    (f for f in archivos if "movie" in f.name.lower()),
    None
)
archivo_series = next(
    (f for f in archivos if "tv" in f.name.lower() or "show" in f.name.lower()),
    None
)

if archivo_peliculas is None or archivo_series is None:
    raise FileNotFoundError(
        "No se encontraron ambos archivos. Revisa los nombres en data/raw."
    )

# Leer los archivos sin modificar los originales
peliculas = pd.read_csv(archivo_peliculas)
series = pd.read_csv(archivo_series)

print("PELÍCULAS:", peliculas.shape)
print("SERIES:", series.shape)

display(peliculas.head())
display(series.head())

PELÍCULAS: (16000, 18)
SERIES: (16000, 16)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,"Animation, Family, Adventure",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000,592461732
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,"Fantasy, Adventure, Animation, Family",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000,494879471

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
0,33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
1,32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
2,37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600
3,75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",Czech Republic,2010-03-01,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500
4,33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...","United States of America, Ireland",2010-10-18,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400

In [3]:

print("=== COLUMNAS DE PELÍCULAS ===")
print(peliculas.dtypes)

print("\n=== COLUMNAS DE SERIES ===")
print(series.dtypes)

# Columnas compartidas y exclusivas
columnas_peliculas = set(peliculas.columns)
columnas_series = set(series.columns)

print("\n=== COLUMNAS COMPARTIDAS ===")
print(sorted(columnas_peliculas & columnas_series))

print("\n=== SOLO EN PELÍCULAS ===")
print(sorted(columnas_peliculas - columnas_series))

print("\n=== SOLO EN SERIES ===")
print(sorted(columnas_series - columnas_peliculas))

=== COLUMNAS DE PELÍCULAS ===
show_id           int64
type                str
title               str
director            str
cast                str
country             str
date_added          str
release_year      int64
rating          float64
duration        float64
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
budget            int64
revenue           int64
dtype: object

=== COLUMNAS DE SERIES ===
show_id           int64
type                str
title               str
director            str
cast                str
country             str
date_added          str
release_year      int64
rating          float64
duration            str
genres              str
language            str
description         str
popularity      float64
vote_count        int64
vote_average    float64
dtype: object

=== COLUMNAS COMPARTIDAS ===
['cast', 'country', 'date_added', 'description', 'director', 'duration', 'genres', 'language', 'popularity', 'rating', 'release_year', 'show_id', 'title', 'type', 'vote_average', 'vote_count']

=== SOLO EN PELÍCULAS ===
['budget', 'revenue']

=== SOLO EN SERIES ===
[]

In [4]:

def revisar_calidad(df, nombre):
    print(f"\n{'=' * 45}")
    print(f"CALIDAD DE DATOS: {nombre}")
    print(f"{'=' * 45}")

    print("\nDimensiones:", df.shape)

    print("\nValores faltantes por columna:")
    faltantes = df.isna().sum()
    faltantes = faltantes[faltantes > 0].sort_values(ascending=False)

    if faltantes.empty:
        print("No se encontraron valores faltantes.")
    else:
        print(faltantes)

    print("\nFilas completamente duplicadas:", df.duplicated().sum())

    if "show_id" in df.columns:
        print("Identificadores repetidos:", df["show_id"].duplicated().sum())

    print("\nResumen de columnas numéricas:")
    display(df.describe().T)


revisar_calidad(peliculas, "Películas")
revisar_calidad(series, "Series")

=============================================
CALIDAD DE DATOS: Películas
=============================================

Dimensiones: (16000, 18)

Valores faltantes por columna:
duration       16000
country          466
cast             204
director         132
description      132
genres           107
dtype: int64

Filas completamente duplicadas: 0
Identificadores repetidos: 0

Resumen de columnas numéricas:

,count,mean,std,min,25%,50%,75%,max
show_id,16000.0,5.266582e+05,3.794427e+05,189.00,225725.75000,446817.0000,7.739808e+05,1.440471e+06
release_year,16000.0,2.017500e+03,4.609916e+00,2010.00,2013.75000,2017.5000,2.021250e+03,2.025000e+03
rating,16000.0,5.956368e+00,1.754741e+00,0.00,5.60000,6.3000,6.923000e+00,1.000000e+01
duration,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
popularity,16000.0,2.038473e+01,6.861003e+01,3.86,7.84075,10.9135,1.733650e+01,3.876006e+03
vote_count,16000.0,7.186561e+02,2.080198e+03,0.00,53.00000,138.0000,4.220000e+02,3.711900e+04
vote_average,16000.0,5.956368e+00,1.754741e+00,0.00,5.60000,6.3000,6.923000e+00,1.000000e+01
budget,16000.0,8.766792e+06,2.912450e+07,0.00,0.00000,0.0000,2.200000e+06,4.600000e+08
revenue,16000.0,2.446308e+07,1.116977e+08,0.00,0.00000,0.0000,1.654473e+06,2.799439e+09

=============================================
CALIDAD DE DATOS: Series
=============================================

Dimensiones: (16000, 16)

Valores faltantes por columna:
director       10965
description     3206
country         1797
cast            1157
genres           974
dtype: int64

Filas completamente duplicadas: 0
Identificadores repetidos: 9

Resumen de columnas numéricas:

,count,mean,std,min,25%,50%,75%,max
show_id,16000.0,126567.673375,75640.760545,767.000,67867.75000,94380.5000,206920.7500,285345.000
release_year,16000.0,2017.500000,4.609916,2010.000,2013.75000,2017.5000,2021.2500,2025.000
rating,16000.0,5.417107,3.266492,0.000,2.70000,6.8000,7.8000,10.000
popularity,16000.0,64.850984,139.387289,2.323,24.87475,36.1875,62.1875,6421.923
vote_count,16000.0,107.014313,607.461581,0.000,1.00000,4.0000,30.0000,24664.000
vote_average,16000.0,5.417107,3.266492,0.000,2.70000,6.8000,7.8000,10.000

In [5]:

campos_numericos = [
    "release_year",
    "popularity",
    "vote_average",
    "vote_count",
    "budget",
    "revenue"
]

for nombre, df in [("Películas", peliculas), ("Series", series)]:
    print(f"\n=== {nombre.upper()} ===")

    for campo in campos_numericos:
        if campo in df.columns:
            print(f"\n{campo}")
            print("Mínimo:", df[campo].min())
            print("Máximo:", df[campo].max())
            print("Valores faltantes:", df[campo].isna().sum())

=== PELÍCULAS ===

release_year
Mínimo: 2010
Máximo: 2025
Valores faltantes: 0

popularity
Mínimo: 3.86
Máximo: 3876.006
Valores faltantes: 0

vote_average
Mínimo: 0.0
Máximo: 10.0
Valores faltantes: 0

vote_count
Mínimo: 0
Máximo: 37119
Valores faltantes: 0

budget
Mínimo: 0
Máximo: 460000000
Valores faltantes: 0

revenue
Mínimo: 0
Máximo: 2799439100
Valores faltantes: 0

=== SERIES ===

release_year
Mínimo: 2010
Máximo: 2025
Valores faltantes: 0

popularity
Mínimo: 2.323
Máximo: 6421.923
Valores faltantes: 0

vote_average
Mínimo: 0.0
Máximo: 10.0
Valores faltantes: 0

vote_count
Mínimo: 0
Máximo: 24664
Valores faltantes: 0

In [6]:

# 1. Investigar identificadores repetidos en series
print("=== IDENTIFICADORES REPETIDOS EN SERIES ===")

ids_repetidos = series[
    series["show_id"].duplicated(keep=False)
].sort_values("show_id")

display(ids_repetidos)

# 2. Comprobar si rating y vote_average son iguales
print("\n=== COMPARACIÓN DE VALORACIONES ===")

for nombre, df in [("Películas", peliculas), ("Series", series)]:
    if {"rating", "vote_average"}.issubset(df.columns):
        iguales = (
            df["rating"].eq(df["vote_average"])
            | (df["rating"].isna() & df["vote_average"].isna())
        )
        print(f"{nombre}: columnas iguales en {iguales.sum()} de {len(df)} registros")

# 3. Analizar valores cero en campos relevantes
print("\n=== VALORES CERO ===")

for nombre, df in [("Películas", peliculas), ("Series", series)]:
    print(f"\n{nombre}")

    for campo in ["vote_average", "vote_count", "budget", "revenue"]:
        if campo in df.columns:
            print(f"{campo}: {(df[campo] == 0).sum()} registros con cero")

# 4. Revisar las fechas de incorporación
print("\n=== FECHAS DE INCORPORACIÓN ===")

for nombre, df in [("Películas", peliculas), ("Series", series)]:
    if "date_added" in df.columns:
        fechas = pd.to_datetime(df["date_added"], errors="coerce")
        print(f"\n{nombre}")
        print("Fechas válidas:", fechas.notna().sum())
        print("Fechas no interpretables:", fechas.isna().sum())
        print("Fecha más antigua:", fechas.min())
        print("Fecha más reciente:", fechas.max())

=== IDENTIFICADORES REPETIDOS EN SERIES ===

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
15540,252630,TV Show,Joe Lycett’s United States of Birmingham,Nicola Silk,Joe Lycett,United Kingdom,2025-03-01,2025,0.0,1 Seasons,"Documentary, Comedy",en,"It’s no secret that Joe Lycett adores Brum, bu...",11.531,0,0.0
15539,252630,TV Show,Joe Lycett’s United States of Birmingham,Nicola Silk,Joe Lycett,United Kingdom,2025-03-01,2025,0.0,1 Seasons,"Documentary, Comedy",en,"It’s no secret that Joe Lycett adores Brum, bu...",11.550,0,0.0
15358,278867,TV Show,Ensemble,Hayato Kawai,"Haruna Kawaguchi, Hokuto Matsumura, Neru Nagah...",Japan,2025-01-18,2025,7.0,1 Seasons,"Drama, Mystery",ja,"Lawyer Sena Koyama, a realist disillusioned by...",11.044,1,7.0
15360,278867,TV Show,Ensemble,Hayato Kawai,"Haruna Kawaguchi, Hokuto Matsumura, Neru Nagah...",Japan,2025-01-18,2025,7.0,1 Seasons,"Drama, Mystery",ja,"Lawyer Sena Koyama, a realist disillusioned by...",18.407,1,7.0
15398,279457,TV Show,Ghassan & Mina,NaN,"Razzaq Ahmed, Sulaf Jalil",NaN,2025-03-01,2025,0.0,1 Seasons,Comedy,ar,NaN,9.631,0,0.0
15400,279457,TV Show,Ghassan & Mina,NaN,"Razzaq Ahmed, Sulaf Jalil",NaN,2025-03-01,2025,0.0,1 Seasons,Comedy,ar,NaN,16.051,0,0.0
15479,279739,TV Show,Settle Down,NaN,"Alexander Nunez, Tymika Tafari, Nadine Bhabha,...",Canada,2025-02-14,2025,0.0,1 Seasons,NaN,en,Mason is an expert on queer relationships and ...,15.215,0,0.0
15480,279739,TV Show,Settle Down,NaN,"Alexander Nunez, Tymika Tafari, Nadine Bhabha,...",Canada,2025-02-14,2025,0.0,1 Seasons,NaN,en,Mason is an expert on queer relationships and ...,13.135,0,0.0
15519,280651,TV Show,Master in 3 Months: Edo Period,NaN,"Hiroyuki Nojima, Noriko Hidaka",Japan,2025-01-08,2025,0.0,1 Seasons,Talk,ja,An easy-to-understand explanation of the Edo P...,16.794,0,0.0
15520,280651,TV Show,Master in 3 Months: Edo Period,NaN,"Hiroyuki Nojima, Noriko Hidaka",Japan,2025-01-08,2025,0.0,1 Seasons,Talk,ja,An easy-to-understand explanation of the Edo P...,11.996,0,0.0
15359,281750,TV Show,الباء تحته نقطة,NaN,"Mohammad Kheir al-Jarrah, Sawsan Badr, جابر نغ...",United Arab Emirates,2025-03-01,2025,0.0,1 Seasons,"Drama, Comedy",ar,NaN,13.448,0,0.0
15361,281750,TV Show,الباء تحته نقطة,NaN,"Mohammad Kheir al-Jarrah, Sawsan Badr, جابر نغ...",United Arab Emirates,2025-03-01,2025,0.0,1 Seasons,"Drama, Comedy",ar,NaN,18.393,0,0.0
15399,283602,TV Show,رحمة,Mohamed Ali El Mejboud,"Mouna Fettou, Abdellah Didane, Karima Gouit, F...",Morocco,2025-03-02,2025,0.0,1 Seasons,Drama,ar,"After years of believing, I find mercy in a to...",22.466,0,0.0
15401,283602,TV Show,رحمة,Mohamed Ali El Mejboud,"Mouna Fettou, Abdellah Didane, Karima Gouit, F...",Morocco,2025-03-02,2025,0.0,1 Seasons,Drama,ar,"After years of believing, I find mercy in a to...",16.047,0,0.0
15320,283929,TV Show,Kimi wa Mendou na Konyakusha,NaN,NaN,NaN,2025-03-03,2025,0.0,1 Seasons,NaN,ja,NaN,21.172,0,0.0
15319,283929,TV Show,Kimi wa Mendou na Konyakusha,NaN,NaN,NaN,2025-03-03,2025,0.0,1 Seasons,NaN,ja,NaN,24.577,0,0.0
15439,284416,TV Show,Par de ideotas,"Javier G. Williams, Pablo Calasso","Vadhir Derbez, José Eduardo Derbez","United States of America, Mexico",2025-03-07,2025,0.0,1 Seasons,"Reality, Comedy, Documentary",es,Vadhir and José Eduardo Derbez open a pop-up b...,14.680,0,0.0
15440,284416,TV Show,Par de ideotas,"Javier G. Williams, Pablo Calasso","Vadhir Derbez, José Eduardo Derbez","United States of America, Mexico",2025-03-07,2025,0.0,1 Seasons,"Reality, Comedy, Documentary",es,Vadhir and José Eduardo Derbez open a pop-up b...,14.553,0,0.0

=== COMPARACIÓN DE VALORACIONES ===
Películas: columnas iguales en 16000 de 16000 registros
Series: columnas iguales en 16000 de 16000 registros

=== VALORES CERO ===

Películas
vote_average: 899 registros con cero
vote_count: 894 registros con cero
budget: 11153 registros con cero
revenue: 10355 registros con cero

Series
vote_average: 3673 registros con cero
vote_count: 3674 registros con cero

=== FECHAS DE INCORPORACIÓN ===

Películas
Fechas válidas: 16000
Fechas no interpretables: 0
Fecha más antigua: 2010-01-01 00:00:00
Fecha más reciente: 2025-12-25 00:00:00

Series
Fechas válidas: 16000
Fechas no interpretables: 0
Fecha más antigua: 2010-01-01 00:00:00
Fecha más reciente: 2025-12-31 00:00:00

In [7]:

# 1. ¿Los ceros de valoración coinciden con los ceros de votos?
print("=== VALORACIÓN Y CANTIDAD DE VOTOS ===")

for nombre, df in [("Películas", peliculas), ("Series", series)]:
    sin_votos = df["vote_count"].eq(0)
    sin_valoracion = df["vote_average"].eq(0)

    print(f"\n{nombre}")
    print("Sin votos:", sin_votos.sum())
    print("Con valoración cero:", sin_valoracion.sum())
    print("Ambos casos a la vez:", (sin_votos & sin_valoracion).sum())
    print("Sin votos pero con valoración positiva:",
          (sin_votos & df["vote_average"].gt(0)).sum())
    print("Con votos pero con valoración cero:",
          (df["vote_count"].gt(0) & sin_valoracion).sum())


# 2. ¿Cuántas películas sirven para analizar finanzas?
print("\n=== DATOS FINANCIEROS DE PELÍCULAS ===")

presupuesto_valido = peliculas["budget"].gt(0)
ingresos_validos = peliculas["revenue"].gt(0)
ambos_validos = presupuesto_valido & ingresos_validos

print("Presupuesto mayor que cero:", presupuesto_valido.sum())
print("Ingresos mayores que cero:", ingresos_validos.sum())
print("Presupuesto e ingresos mayores que cero:", ambos_validos.sum())
print("Presupuesto o ingresos iguales a cero:",
      (~ambos_validos).sum())


# 3. Examinar identificadores repetidos de series
print("\n=== REGISTROS CON ID REPETIDO EN SERIES ===")

ids_repetidos = series.loc[
    series["show_id"].duplicated(keep=False)
].sort_values("show_id")

columnas_revisar = [
    c for c in [
        "show_id", "title", "release_year",
        "date_added", "country", "genres"
    ] if c in series.columns
]

display(ids_repetidos[columnas_revisar])

=== VALORACIÓN Y CANTIDAD DE VOTOS ===

Películas
Sin votos: 894
Con valoración cero: 899
Ambos casos a la vez: 894
Sin votos pero con valoración positiva: 0
Con votos pero con valoración cero: 5

Series
Sin votos: 3674
Con valoración cero: 3673
Ambos casos a la vez: 3661
Sin votos pero con valoración positiva: 13
Con votos pero con valoración cero: 12

=== DATOS FINANCIEROS DE PELÍCULAS ===
Presupuesto mayor que cero: 4847
Ingresos mayores que cero: 5645
Presupuesto e ingresos mayores que cero: 3540
Presupuesto o ingresos iguales a cero: 12460

=== REGISTROS CON ID REPETIDO EN SERIES ===

,show_id,title,release_year,date_added,country,genres
15540,252630,Joe Lycett’s United States of Birmingham,2025,2025-03-01,United Kingdom,"Documentary, Comedy"
15539,252630,Joe Lycett’s United States of Birmingham,2025,2025-03-01,United Kingdom,"Documentary, Comedy"
15358,278867,Ensemble,2025,2025-01-18,Japan,"Drama, Mystery"
15360,278867,Ensemble,2025,2025-01-18,Japan,"Drama, Mystery"
15398,279457,Ghassan & Mina,2025,2025-03-01,NaN,Comedy
15400,279457,Ghassan & Mina,2025,2025-03-01,NaN,Comedy
15479,279739,Settle Down,2025,2025-02-14,Canada,NaN
15480,279739,Settle Down,2025,2025-02-14,Canada,NaN
15519,280651,Master in 3 Months: Edo Period,2025,2025-01-08,Japan,Talk
15520,280651,Master in 3 Months: Edo Period,2025,2025-01-08,Japan,Talk
15359,281750,الباء تحته نقطة,2025,2025-03-01,United Arab Emirates,"Drama, Comedy"
15361,281750,الباء تحته نقطة,2025,2025-03-01,United Arab Emirates,"Drama, Comedy"
15399,283602,رحمة,2025,2025-03-02,Morocco,Drama
15401,283602,رحمة,2025,2025-03-02,Morocco,Drama
15320,283929,Kimi wa Mendou na Konyakusha,2025,2025-03-03,NaN,NaN
15319,283929,Kimi wa Mendou na Konyakusha,2025,2025-03-03,NaN,NaN
15439,284416,Par de ideotas,2025,2025-03-07,"United States of America, Mexico","Reality, Comedy, Documentary"
15440,284416,Par de ideotas,2025,2025-03-07,"United States of America, Mexico","Reality, Comedy, Documentary"

In [8]:

# 1. Mostrar los nombres reales de todas las columnas
print("=== COLUMNAS REALES DEL DATASET DE SERIES ===")
for i, columna in enumerate(series.columns):
    print(i, repr(columna))

# 2. Comparar los registros que comparten show_id
print("\n=== REGISTROS CON show_id REPETIDO ===")

mascara = series["show_id"].duplicated(keep=False)
repetidos = series.loc[mascara].sort_values("show_id")

display(repetidos)

# 3. Comprobar si son idénticos al ignorar show_id
sin_id = series.drop(columns=["show_id"])
print(
    "\nFilas repetidas al ignorar show_id:",
    sin_id.loc[mascara].duplicated(keep=False).sum()
)

# 4. Buscar títulos repetidos, independientemente del identificador
if "title" in series.columns:
    print("\n=== TÍTULOS REPETIDOS ===")
    titulos_repetidos = series[
        series["title"].duplicated(keep=False)
    ].sort_values("title")

    print("Registros cuyos títulos se repiten:", len(titulos_repetidos))
    display(titulos_repetidos[[
        c for c in ["show_id", "title", "release_year", "date_added"]
        if c in series.columns
    ]].head(30))

=== COLUMNAS REALES DEL DATASET DE SERIES ===
0 'show_id'
1 'type'
2 'title'
3 'director'
4 'cast'
5 'country'
6 'date_added'
7 'release_year'
8 'rating'
9 'duration'
10 'genres'
11 'language'
12 'description'
13 'popularity'
14 'vote_count'
15 'vote_average'

=== REGISTROS CON show_id REPETIDO ===

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
15540,252630,TV Show,Joe Lycett’s United States of Birmingham,Nicola Silk,Joe Lycett,United Kingdom,2025-03-01,2025,0.0,1 Seasons,"Documentary, Comedy",en,"It’s no secret that Joe Lycett adores Brum, bu...",11.531,0,0.0
15539,252630,TV Show,Joe Lycett’s United States of Birmingham,Nicola Silk,Joe Lycett,United Kingdom,2025-03-01,2025,0.0,1 Seasons,"Documentary, Comedy",en,"It’s no secret that Joe Lycett adores Brum, bu...",11.550,0,0.0
15358,278867,TV Show,Ensemble,Hayato Kawai,"Haruna Kawaguchi, Hokuto Matsumura, Neru Nagah...",Japan,2025-01-18,2025,7.0,1 Seasons,"Drama, Mystery",ja,"Lawyer Sena Koyama, a realist disillusioned by...",11.044,1,7.0
15360,278867,TV Show,Ensemble,Hayato Kawai,"Haruna Kawaguchi, Hokuto Matsumura, Neru Nagah...",Japan,2025-01-18,2025,7.0,1 Seasons,"Drama, Mystery",ja,"Lawyer Sena Koyama, a realist disillusioned by...",18.407,1,7.0
15398,279457,TV Show,Ghassan & Mina,NaN,"Razzaq Ahmed, Sulaf Jalil",NaN,2025-03-01,2025,0.0,1 Seasons,Comedy,ar,NaN,9.631,0,0.0
15400,279457,TV Show,Ghassan & Mina,NaN,"Razzaq Ahmed, Sulaf Jalil",NaN,2025-03-01,2025,0.0,1 Seasons,Comedy,ar,NaN,16.051,0,0.0
15479,279739,TV Show,Settle Down,NaN,"Alexander Nunez, Tymika Tafari, Nadine Bhabha,...",Canada,2025-02-14,2025,0.0,1 Seasons,NaN,en,Mason is an expert on queer relationships and ...,15.215,0,0.0
15480,279739,TV Show,Settle Down,NaN,"Alexander Nunez, Tymika Tafari, Nadine Bhabha,...",Canada,2025-02-14,2025,0.0,1 Seasons,NaN,en,Mason is an expert on queer relationships and ...,13.135,0,0.0
15519,280651,TV Show,Master in 3 Months: Edo Period,NaN,"Hiroyuki Nojima, Noriko Hidaka",Japan,2025-01-08,2025,0.0,1 Seasons,Talk,ja,An easy-to-understand explanation of the Edo P...,16.794,0,0.0
15520,280651,TV Show,Master in 3 Months: Edo Period,NaN,"Hiroyuki Nojima, Noriko Hidaka",Japan,2025-01-08,2025,0.0,1 Seasons,Talk,ja,An easy-to-understand explanation of the Edo P...,11.996,0,0.0
15359,281750,TV Show,الباء تحته نقطة,NaN,"Mohammad Kheir al-Jarrah, Sawsan Badr, جابر نغ...",United Arab Emirates,2025-03-01,2025,0.0,1 Seasons,"Drama, Comedy",ar,NaN,13.448,0,0.0
15361,281750,TV Show,الباء تحته نقطة,NaN,"Mohammad Kheir al-Jarrah, Sawsan Badr, جابر نغ...",United Arab Emirates,2025-03-01,2025,0.0,1 Seasons,"Drama, Comedy",ar,NaN,18.393,0,0.0
15399,283602,TV Show,رحمة,Mohamed Ali El Mejboud,"Mouna Fettou, Abdellah Didane, Karima Gouit, F...",Morocco,2025-03-02,2025,0.0,1 Seasons,Drama,ar,"After years of believing, I find mercy in a to...",22.466,0,0.0
15401,283602,TV Show,رحمة,Mohamed Ali El Mejboud,"Mouna Fettou, Abdellah Didane, Karima Gouit, F...",Morocco,2025-03-02,2025,0.0,1 Seasons,Drama,ar,"After years of believing, I find mercy in a to...",16.047,0,0.0
15320,283929,TV Show,Kimi wa Mendou na Konyakusha,NaN,NaN,NaN,2025-03-03,2025,0.0,1 Seasons,NaN,ja,NaN,21.172,0,0.0
15319,283929,TV Show,Kimi wa Mendou na Konyakusha,NaN,NaN,NaN,2025-03-03,2025,0.0,1 Seasons,NaN,ja,NaN,24.577,0,0.0
15439,284416,TV Show,Par de ideotas,"Javier G. Williams, Pablo Calasso","Vadhir Derbez, José Eduardo Derbez","United States of America, Mexico",2025-03-07,2025,0.0,1 Seasons,"Reality, Comedy, Documentary",es,Vadhir and José Eduardo Derbez open a pop-up b...,14.680,0,0.0
15440,284416,TV Show,Par de ideotas,"Javier G. Williams, Pablo Calasso","Vadhir Derbez, José Eduardo Derbez","United States of America, Mexico",2025-03-07,2025,0.0,1 Seasons,"Reality, Comedy, Documentary",es,Vadhir and José Eduardo Derbez open a pop-up b...,14.553,0,0.0

Filas repetidas al ignorar show_id: 0

=== TÍTULOS REPETIDOS ===
Registros cuyos títulos se repiten: 607

       show_id                     title  release_year  date_added
9072     97881  100 días para enamorarse          2019  2019-12-09
8124     80719  100 días para enamorarse          2018  2018-05-07
4156     61546                      19-2          2014  2014-01-29
1844     38527                      19-2          2011  2011-02-02
14865   225467                      1992          2024  2024-12-13
5744     62459                      1992          2015  2015-03-24
4324     66957                3 Familias          2014  2014-03-31
7137    230609                3 Familias          2017  2017-10-23
6601    214190              A Happy Life          2016  2016-01-13
3126     97367              A Happy Life          2013  2013-06-30
12925   107005     A League of Their Own          2022  2022-08-11
53       32348     A League of Their Own          2010  2010-03-11
10203   114395       A Love So Beautiful          2020  2020-12-28
14923   232670       A Love So Beautiful          2024  2024-06-03
7296     75387       A Love So Beautiful          2017  2017-11-09
9200     95885           A Mother's Love          2019  2019-11-25
12007    49608           A Mother's Love          2022  2022-02-14
679      32940                   Accused          2010  2010-11-15
13233   202097                   Accused          2023  2023-01-22
10014   110316       Alice in Borderland          2020  2020-12-10
4950     71907       Alice in Borderland          2014  2014-10-17
6120     90487                    Amanda          2016  2016-11-22
6253     51788                    Amanda          2016  2016-09-05
10339   101102          Are You The One?          2020  2020-04-14
4249     61535          Are You The One?          2014  2014-01-21
4653     67048                 Barakamon          2014  2014-07-05
13556   228498                 Barakamon          2023  2023-07-12
13629   234133               Be with You          2023  2023-09-06
5529    132124               Be with You          2015  2015-04-14
5280    220972            Because of You          2015  2015-11-30

In [9]:

# Obtener todos los registros que comparten show_id
mascara = series["show_id"].duplicated(keep=False)
repetidos = series.loc[mascara].sort_values("show_id")

# Mostrar solo las columnas que realmente cambian dentro de cada grupo
columnas_comparar = [
    c for c in series.columns if c != "show_id"
]

print("=== DIFERENCIAS ENTRE REGISTROS CON EL MISMO show_id ===")

for identificador, grupo in repetidos.groupby("show_id"):
    diferencias = []

    for columna in columnas_comparar:
        valores = grupo[columna].drop_duplicates()

        # Considerar también los valores faltantes
        if grupo[columna].nunique(dropna=False) > 1:
            diferencias.append(columna)

    print(f"\nshow_id: {identificador}")
    print("Cantidad de registros:", len(grupo))
    print("Columnas diferentes:", diferencias)

    display(grupo[["show_id"] + diferencias])

=== DIFERENCIAS ENTRE REGISTROS CON EL MISMO show_id ===

show_id: 252630
Cantidad de registros: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15540   252630      11.531
15539   252630      11.550

show_id: 278867
Cantidad de registros: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15358   278867      11.044
15360   278867      18.407

show_id: 279457
Cantidad de registros: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15398   279457       9.631
15400   279457      16.051

show_id: 279739
Cantidad de registros: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15479   279739      15.215
15480   279739      13.135

show_id: 280651
Cantidad de registros: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15519   280651      16.794
15520   280651      11.996

show_id: 281750
Cantidad de registros: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15359   281750      13.448
15361   281750      18.393

show_id: 283602
Cantidad de registros: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15399   283602      22.466
15401   283602      16.047

show_id: 283929
Cantidad de registros: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15320   283929      21.172
15319   283929      24.577

show_id: 284416
Cantidad de registros: 2
Columnas diferentes: ['popularity']

       show_id  popularity
15439   284416      14.680
15440   284416      14.553

In [10]:

from pathlib import Path
import pandas as pd

# Crear la carpeta de salida si todavía no existe
carpeta_procesados = Path("../data/processed")
carpeta_procesados.mkdir(parents=True, exist_ok=True)

# Trabajar sobre copias, nunca sobre los originales
peliculas_procesadas = peliculas.copy()
series_procesadas = series.copy()

# Consolidar series que comparten show_id:
# mantener los demás campos y promediar popularity
popularidad_promedio = (
    series_procesadas
    .groupby("show_id")["popularity"]
    .mean()
)

series_procesadas["popularity"] = (
    series_procesadas["show_id"].map(popularidad_promedio)
)

# Conservar una fila por show_id
series_procesadas = series_procesadas.drop_duplicates(
    subset="show_id",
    keep="first"
).copy()

# Guardar los archivos procesados
ruta_peliculas = carpeta_procesados / "peliculas_procesadas.csv"
ruta_series = carpeta_procesados / "series_procesadas.csv"

peliculas_procesadas.to_csv(ruta_peliculas, index=False)
series_procesadas.to_csv(ruta_series, index=False)

# Comprobar el resultado
print("=== ARCHIVOS PROCESADOS ===")
print("Películas:", peliculas_procesadas.shape)
print("Series:", series_procesadas.shape)

print(
    "Identificadores repetidos restantes en series:",
    series_procesadas["show_id"].duplicated().sum()
)

print("\nArchivos guardados en:")
print(ruta_peliculas)
print(ruta_series)

=== ARCHIVOS PROCESADOS ===
Películas: (16000, 18)
Series: (15991, 16)
Identificadores repetidos restantes en series: 0

Archivos guardados en:
..\data\processed\peliculas_procesadas.csv
..\data\processed\series_procesadas.csv